export enum ActionsType {
	FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS',
	FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL',
	CHANGE_QUESTION_NUMBER = 'CHANGE_QUESTION_NUMBER',
	CHANGE_QUESTION_VIEW = 'CHANGE_QUESTION_VIEW',
	FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST',
	CHANGE_QUESTION_REQUEST = 'CHANGE_QUESTION_REQUEST',
}
